import type { Metadata } from "next";
import Sidebar from "./_components/Sidebar";
import Navbar from "./_components/Navbar";
import SidebarProvider from "@/context/SidebarContext";

export const metadata: Metadata = {
    title: "Admin",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="min-h-full flex flex-col">
                <SidebarProvider>
                    <div className="min-h-screen bg-gray-100">
                        <Navbar />
                        <div className="flex">
                            <Sidebar />
                            <main className="flex-1 p-4 md:p-6 lg:p-8 overflow-x-hidden h-[calc(100vh-64px)]">
                                <div className="p-6 bg-white rounded-2xl shadow-sm min-h-125">
                                    {children}
                                </div>
                            </main>
                        </div>
                    </div>
                </SidebarProvider>
            </body>
        </html>
    );
}
